
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Keerthana
 */
public class Booking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public Booking() {
        initComponents();
        setBounds(100,200,1100,665);
        billheader();
    }

    private void billheader(){
        bill.setText("===================="+"\n"
        +"      Wedding Planner"+"\n"
        +"===================="+"\n\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        pricingsstd = new javax.swing.JLabel();
        pricingspro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        hours = new javax.swing.JTextField();
        std = new javax.swing.JRadioButton();
        pro = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        totalamount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        generatebill = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 40, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pricings (Standard)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 90, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pricings (Professional)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 140, 210, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hours Needed");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 270, 130, 30);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(name);
        name.setBounds(310, 50, 190, 30);

        pricingsstd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(pricingsstd);
        pricingsstd.setBounds(310, 90, 190, 30);

        pricingspro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(pricingspro);
        pricingspro.setBounds(310, 130, 190, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("GO BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 490, 150, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Service Type");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 340, 120, 30);

        hours.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hours.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        hours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursActionPerformed(evt);
            }
        });
        jPanel1.add(hours);
        hours.setBounds(300, 270, 190, 40);

        std.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(std);
        std.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        std.setText("Standard");
        jPanel1.add(std);
        std.setBounds(290, 340, 130, 40);

        pro.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(pro);
        pro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pro.setText("Professional");
        pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proActionPerformed(evt);
            }
        });
        jPanel1.add(pro);
        pro.setBounds(450, 340, 140, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("CALCULATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 490, 170, 50);

        totalamount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(totalamount);
        totalamount.setBounds(70, 550, 160, 50);

        bill.setColumns(20);
        bill.setRows(5);
        jScrollPane1.setViewportView(bill);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(650, 60, 410, 368);

        generatebill.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        generatebill.setText("GENERATE BILL");
        generatebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebillActionPerformed(evt);
            }
        });
        jPanel1.add(generatebill);
        generatebill.setBounds(650, 440, 410, 70);

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(username);
        username.setBounds(890, 550, 120, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(190, 550, 160, 60);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 770, 0);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Time / date ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 190, 120, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Place");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 230, 70, 30);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(310, 180, 100, 30);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(310, 230, 80, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\Documents\\wedding_planner\\icon\\f1.jpg")); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 0, 650, 620);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String x = username.getText();
        Details menu = new Details();
        menu.username.setText(x);
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void hoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoursActionPerformed

    private void proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String value1 = name.getText();
        double value2 = Double.parseDouble(pricingsstd.getText());
        double value3 = Double.parseDouble(pricingspro.getText());
        double value4 = Double.parseDouble(hours.getText());
        if(std.isSelected()){
            double valuex = value2*value4;
            String result = String.format("%.0f", valuex);
            totalamount.setText(result);
            bill.setText(
                    bill.getText()+"Vendor         --        Pricing   --   Hours   --   Total\n"+
                                    value1+"   --   "+value2+"   --   "+value4+"   --   "+result
            );
        }
        if(pro.isSelected()){
            double valuex = value3*value4;
            String result = String.format("%.0f", valuex);
            totalamount.setText(result);
            bill.setText(
                    bill.getText()+"Vendor         --        Pricing   --   Hours   --   Total\n"+
                                    value1+"   --   "+value3+"   --   "+value4+"   --   "+result
            );
        }
         try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/wedding_java", "root", "");
                String sql = "INSERT INTO vendor_count (name, username, amount)"+"values(?,?,?)";
                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, name.getText());
                pst.setString(2, username.getText());
                pst.setString(3, totalamount.getText());
 
                pst.execute();                
                con.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void generatebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebillActionPerformed
        try {
            bill.print();
        } catch (PrinterException ex) {
            
        }
    }//GEN-LAST:event_generatebillActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bill;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton generatebill;
    private javax.swing.JTextField hours;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel name;
    public static javax.swing.JLabel pricingspro;
    public static javax.swing.JLabel pricingsstd;
    private javax.swing.JRadioButton pro;
    private javax.swing.JRadioButton std;
    private javax.swing.JLabel totalamount;
    public static javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
